version: '3'

services:
  db:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
  web:
    build: .
    restart: unless-stopped
    links:
      - "db:database"
    environment:
      - MONGO_DB_URL=mongodb://database:27017/0
      - PORT=8080
    ports:
      - "11882:8080"
    depends_on:
      - db