version: 2
jobs:
  build:
    docker:
      - image: python:3.6.8-slim-stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip3 install -r requirements.txt
  test:
    docker:
      - image: python:3.6.8-slim-stretch
    steps:
      - run:
          name: Run pytests
          command: |
            coverage run --source app -m pytest
      - run:
          command: |
            coverage html
      - store_artifacts:
          path: htmlcov/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
